# Generated by Django 4.2 on 2023-05-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pintura',
            fields=[
                ('idPintura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('artista', models.CharField(default='', max_length=100)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('foto', models.ImageField(default='fotos/pinturaDefault.png', null=True, upload_to='fotos')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
