# Generated by Django 4.2 on 2023-05-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wepPintura', '0002_categoria_pintura_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='pintura',
            name='artista',
        ),
        migrations.AddField(
            model_name='pintura',
            name='Artista',
            field=models.ForeignKey(default='nuevo', on_delete=django.db.models.deletion.CASCADE, to='wepPintura.artista'),
        ),
    ]
