# Generated by Django 4.2 on 2023-05-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wepPintura', '0003_artista_remove_pintura_artista_pintura_artista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pintura',
            old_name='Artista',
            new_name='artista',
        ),
    ]
